Updates the README and Bug/Documentation reporting templates
Andrewthe13th/Inventory_Kamera pull request #342
Opened 2022-07-29 03:41 UTC by mineminemine

Fixes some typos, grammar errors and whatnot

2022-07-29 23:58 UTC, Cupcak3 requested changes
Some comments on specific line changes. If a change doesn't have a comment it's ok.

2022-07-29 23:58 UTC, Cupcak3 commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: "What behaviour would you have expected to see?"
I would ask that American English preferred spelling be used for words.

2022-07-29 23:58 UTC, Cupcak3 commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: In which Genshin Impact version did this issue happen?
Description should be something like "Which Genshin Impact version does this issue affect?"

2022-07-29 23:58 UTC, Cupcak3 commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: Which Inventory Kamera version did you use?
The original description is fine or something like "Which version of Inventory Kamera is affected?"

2022-07-29 23:58 UTC, Cupcak3 commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: What screen resolution(s), screen mode, and UI scale are you using?
Original description is fine

2022-07-29 23:58 UTC, Cupcak3 commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        - label: "I have checked the issue page, and there are none that similar to the one I'm reporting."
Better description "I have checked for similar issues and found nothing similar"

2022-07-29 23:58 UTC, Cupcak3 commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        - label: "I will be available to explain the issue."
This field doesn't even need to exist

2022-07-29 23:58 UTC, Cupcak3 commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        - label: "I did not enable any image filtering software or plugins (i.e. HDR, Image Sharpening, etc.) while scanning."
Better description "I have disabled any and all screen filtering software or plugins (HDR, Image Sharpening, etc.)"

2022-07-29 23:58 UTC, Cupcak3 commented on README.md
> +A fan-made Genshin Impact tool that scans your Characters, Weapons, Artifacts, Materials, and Character Development items in your Inventory using the OCR technique.
Unnecessary

2022-07-29 23:58 UTC, Cupcak3 commented on README.md
> +This scanner exports in `.GOOD`, a JSON-based  export format, which allows you to use it with compatible online Genshin Impact tools. These tools include artifact optimizing tools including [Genshin
Unnecessary

2022-07-29 23:58 UTC, Cupcak3 commented on README.md
> +   - Under `Languages`, set the *Game Language* to English.
Unnecessary

2022-07-29 23:58 UTC, Cupcak3 commented on README.md
> +   - Under `Graphics`, set the *Display Mode* to *any windowed resolution* that is *16:9 or 16:10 ratio*. Make sure that the entire game window is visible on the screen.
Unnecessary

2022-07-29 23:58 UTC, Cupcak3 commented on README.md
> +      - If you have rebounded the inventory key (default: B) or character screen key (default: C), either revert your binding to default or set the key binding in Inventory Kamera.
Rebound is appropriate. Sentence should probably read something like "If you have rebound a key, make sure to bind the keys appropriately in Inventory Kamera"

2022-07-29 23:58 UTC, Cupcak3 commented on README.md
> +- Configure the minimum weapon and artifact rarity to be scanned.
Unnecessary

2022-07-29 23:58 UTC, Cupcak3 commented on README.md
> +> While scanning, **do not use your mouse or keyboard**. The scanner uses mouse and keyboard inputs to automate artifact scanning.
Remove 'artifact'

2022-07-30 01:51 UTC, sagelga requested changes

2022-07-30 01:51 UTC, sagelga commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      value: "Please describe the bug as best as you can. This will speed up our bug fixing process."
Most of the users don't even understand what the bug is. 

All they want is to enjoy Genshin and use the scanner.

I suggests we choose wording for normal person.

2022-07-30 01:51 UTC, sagelga commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: "What operating system are you using? (e.g., Windows, Mac, Linux)"
Confused on why the , after e.g.

2022-07-30 01:51 UTC, sagelga commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        - label: "I will be available to explain the issue."
Pretty much to let the user understands that they might have to provide us more information for fixing the issue.

2022-07-30 01:51 UTC, sagelga commented on .github/ISSUE_TEMPLATE/fallback_template.yml
> +        - label: "I understand that this is not a feature request or enhancement request. Requests can be made in the Discussions tab."
Not can in "done in Discussions tab" but a must.

2022-07-30 01:51 UTC, sagelga commented on .github/ISSUE_TEMPLATE/fallback_template.yml
> +        - label: "I understand that this is not a question, a crash report, an error report, or a bug report. Bug reports can be reported in Issues > Bug Report."
Same here as prev. line

2022-07-30 02:02 UTC, closed without merging